Bridge.assembly("FarseerPhysics.Demo", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = ["System","FarseerPhysics.Dynamics","FarseerPhysics.Utility","Microsoft.Xna.Framework","Microsoft.Xna.Framework.Graphics","System.Collections.Generic","FarseerPhysics.Samples"];
    $m("FarseerPhysics.Demo.App", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void}]}; }, $n);
    $m("FarseerPhysics.Samples.Agent", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[1].World,$n[2].ScreenManager,$n[3].Vector2],"pi":[{"n":"world","pt":$n[1].World,"ps":0},{"n":"screenManager","pt":$n[2].ScreenManager,"ps":1},{"n":"position","pt":$n[3].Vector2,"ps":2}],"sn":"ctor"},{"a":2,"n":"Draw","t":8,"sn":"Draw","rt":$n[0].Void},{"a":2,"n":"Body","t":16,"rt":$n[1].Body,"g":{"a":2,"n":"get_Body","t":8,"rt":$n[1].Body,"fg":"Body"},"fn":"Body"},{"a":1,"n":"_agentBody","t":4,"rt":$n[1].Body,"sn":"_agentBody"},{"a":1,"n":"_batch","t":4,"rt":$n[4].SpriteBatch,"sn":"_batch"},{"a":1,"n":"radius","t":4,"rt":$n[0].Single,"sn":"radius","box":function ($v) { return Bridge.box($v, System.Single, System.Single.format, System.Single.getHashCode);}},{"a":1,"n":"sprite","t":4,"rt":$n[2].Sprite,"sn":"sprite"}]}; }, $n);
    $m("FarseerPhysics.Samples.PhysicsGame", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":3,"n":"Initialize","t":8,"sn":"Initialize","rt":$n[0].Void},{"a":2,"n":"ScreenManager","t":16,"rt":$n[2].ScreenManager,"g":{"a":2,"n":"get_ScreenManager","t":8,"rt":$n[2].ScreenManager,"fg":"ScreenManager"},"s":{"a":2,"n":"set_ScreenManager","t":8,"p":[$n[2].ScreenManager],"rt":$n[0].Void,"fs":"ScreenManager"},"fn":"ScreenManager"},{"a":1,"n":"_graphics","t":4,"rt":$n[3].GraphicsDeviceManager,"sn":"_graphics"}]}; }, $n);
    $m("FarseerPhysics.Samples.Pyramid", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[1].World,$n[2].ScreenManager,$n[3].Vector2,$n[0].Int32,$n[0].Single],"pi":[{"n":"world","pt":$n[1].World,"ps":0},{"n":"screenManager","pt":$n[2].ScreenManager,"ps":1},{"n":"position","pt":$n[3].Vector2,"ps":2},{"n":"count","pt":$n[0].Int32,"ps":3},{"n":"density","pt":$n[0].Single,"ps":4}],"sn":"ctor"},{"a":2,"n":"Draw","t":8,"sn":"Draw","rt":$n[0].Void},{"a":1,"n":"_batch","t":4,"rt":$n[4].SpriteBatch,"sn":"_batch"},{"a":1,"n":"_box","t":4,"rt":$n[2].Sprite,"sn":"_box"},{"a":1,"n":"_boxes","t":4,"rt":$n[5].List$1(FarseerPhysics.Dynamics.Body),"sn":"_boxes"},{"a":1,"n":"width","t":4,"rt":$n[0].Single,"sn":"width","box":function ($v) { return Bridge.box($v, System.Single, System.Single.format, System.Single.getHashCode);}}]}; }, $n);
    $m("FarseerPhysics.Samples.Demos.DemoGameScreen", function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[2].ScreenManager],"pi":[{"n":"screenManager","pt":$n[2].ScreenManager,"ps":0}],"sn":"ctor"},{"ov":true,"a":2,"n":"Draw","t":8,"pi":[{"n":"gameTime","pt":$n[3].GameTime,"ps":0}],"sn":"Draw","rt":$n[0].Void,"p":[$n[3].GameTime]},{"ov":true,"a":2,"n":"LoadContent","t":8,"sn":"LoadContent","rt":$n[0].Void},{"ov":true,"a":2,"n":"Update","t":8,"pi":[{"n":"gameTime","pt":$n[3].GameTime,"ps":0},{"n":"otherScreenHasFocus","pt":$n[0].Boolean,"ps":1},{"n":"coveredByOtherScreen","pt":$n[0].Boolean,"ps":2}],"sn":"Update","rt":$n[0].Void,"p":[$n[3].GameTime,$n[0].Boolean,$n[0].Boolean]},{"a":1,"n":"PyramidBaseBodyCount","is":true,"t":4,"rt":$n[0].Int32,"sn":"PyramidBaseBodyCount","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":1,"n":"_pyramid","t":4,"rt":$n[6].Pyramid,"sn":"_pyramid"},{"a":1,"n":"agent","t":4,"rt":$n[6].Agent,"sn":"agent"},{"a":1,"n":"background","t":4,"rt":$n[4].Texture2D,"sn":"background"},{"a":1,"n":"didPress","t":4,"rt":$n[0].Boolean,"sn":"didPress","box":function ($v) { return Bridge.box($v, System.Boolean, System.Boolean.toString);}},{"a":1,"n":"touchOff","t":4,"rt":$n[3].Vector2,"sn":"touchOff"},{"a":1,"n":"touchOn","t":4,"rt":$n[3].Vector2,"sn":"touchOn"}]}; }, $n);
});
