Bridge.assembly("FarseerPhysics.Demo", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = ["System","FarseerPhysics.Utility","Microsoft.Xna.Framework","FarseerPhysics.Dynamics","Microsoft.Xna.Framework.Graphics","System.Collections.Generic","FarseerPhysics.Samples"];
    $m("FarseerPhysics.Samples.PhysicsGame", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":3,"n":"Initialize","t":8,"sn":"Initialize","rt":$n[0].Void},{"a":2,"n":"ScreenManager","t":16,"rt":$n[1].ScreenManager,"g":{"a":2,"n":"get_ScreenManager","t":8,"rt":$n[1].ScreenManager,"fg":"ScreenManager"},"s":{"a":2,"n":"set_ScreenManager","t":8,"p":[$n[1].ScreenManager],"rt":$n[0].Void,"fs":"ScreenManager"},"fn":"ScreenManager"},{"a":1,"n":"_graphics","t":4,"rt":$n[2].GraphicsDeviceManager,"sn":"_graphics"}]}; }, $n);
    $m("FarseerPhysics.Samples.Pyramid", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[3].World,$n[1].ScreenManager,$n[2].Vector2,$n[0].Int32,$n[0].Single],"pi":[{"n":"world","pt":$n[3].World,"ps":0},{"n":"screenManager","pt":$n[1].ScreenManager,"ps":1},{"n":"position","pt":$n[2].Vector2,"ps":2},{"n":"count","pt":$n[0].Int32,"ps":3},{"n":"density","pt":$n[0].Single,"ps":4}],"sn":"ctor"},{"a":2,"n":"Draw","t":8,"sn":"Draw","rt":$n[0].Void},{"a":1,"n":"_batch","t":4,"rt":$n[4].SpriteBatch,"sn":"_batch"},{"a":1,"n":"_box","t":4,"rt":$n[1].Sprite,"sn":"_box"},{"a":1,"n":"_boxes","t":4,"rt":$n[5].List$1(FarseerPhysics.Dynamics.Body),"sn":"_boxes"},{"a":1,"n":"width","t":4,"rt":$n[0].Single,"sn":"width","box":function ($v) { return Bridge.box($v, System.Single, System.Single.format, System.Single.getHashCode);}}]}; }, $n);
    $m("FarseerPhysics.Samples.Demos.DemoGameScreen", function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[1].ScreenManager],"pi":[{"n":"screenManager","pt":$n[1].ScreenManager,"ps":0}],"sn":"ctor"},{"ov":true,"a":2,"n":"Draw","t":8,"pi":[{"n":"gameTime","pt":$n[2].GameTime,"ps":0}],"sn":"Draw","rt":$n[0].Void,"p":[$n[2].GameTime]},{"ov":true,"a":2,"n":"LoadContent","t":8,"sn":"LoadContent","rt":$n[0].Void},{"a":1,"n":"PyramidBaseBodyCount","is":true,"t":4,"rt":$n[0].Int32,"sn":"PyramidBaseBodyCount","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":1,"n":"_pyramid","t":4,"rt":$n[6].Pyramid,"sn":"_pyramid"},{"a":1,"n":"background","t":4,"rt":$n[4].Texture2D,"sn":"background"}]}; }, $n);
    $m("FarseerPhysics.Demo.App", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void}]}; }, $n);
});
